name: day_night_switch
description: A day night switch widget for Flutter.
version: 1.0.0
homepage: https://github.com/divyanshub024/day_night_switch
repository: https://github.com/divyanshub024/day_night_switch
issue_tracker: https://github.com/divyanshub024/day_night_switch/issues
documentation: https://github.com/divyanshub024/day_night_switch/blob/master/README.md

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
